---
- hosts: ubuntu
  gather_facts: yes
  roles:
   - nginx
  tags: web

- hosts: ubuntu
  gather_facts: no
  roles:
   - sites
  tags: site

- hosts: ubuntu
  gather_facts: no
  roles:
   - system
  tags: system
